version: "3.5"
services:
  postgres:
    container_name: postgres_db
    image: postgres
    expose:
      - "5432"
    env_file:
      - ./config/postgres.env
    volumes:
      - ./pg_volume:/var/lib/postgresql/data
      - ./services/postgres/docker/00_create_user.sh:/docker-entrypoint-initdb.d/00_create_user.sh
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pg_admin:
    container_name: pg_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "bartner@msn.com"
      PGADMIN_DEFAULT_PASSWORD: "start.123"
      PGADMIN_LISTEN_PORT: 80
    volumes:
       - ./pg_admin:/root/.pgadmin     
    ports:
      - 5050:80
    links:
      - "postgres:psql-server"
    depends_on:
      - postgres
    networks:
      - postgres
    restart: unless-stopped
    
  flask:
    container_name: "Webservice"
    build: services/flask/docker/.
    volumes:
      - ./services/flask/docker:/app
    depends_on: 
      - postgres
    ports:
      - 5000:5000
    networks:
      - postgres
    restart: always
      
  #portainer:
  #container_name: "Controller"
  #restart: "always"
  #image: portainer/portainer
  #volumes: 
  #-/var/run/docker.sock:/var/run/docker.sock
  #ports:
  #- 9090:9000
  #command: 
  #-H unix:///var/run/docker.sock

networks:
  postgres:
    name: pg_drive
    driver: bridge
    
volumes:
  pg_volume:
  pg_admin:
